apiVersion: v1
kind: Service
metadata:
  name: {{ include "horizon-self-service-cicd-pipeline-backend.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "horizon-self-service-cicd-pipeline-backend.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "horizon-self-service-cicd-pipeline-backend.fullname" . }}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 8000
